import './globals.css'
import { Inter } from 'next/font/google'

const Inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Inter.className}>{children}</body>
    </html>
  )
}
