import './globals.css'
import { Cormorant } from 'next/font/google'

const Cormorant = Cormorant({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Cormorant.className}>{children}</body>
    </html>
  )
}
